// Verbatim enum lists from BetterContact OpenAPI spec.
// BC will 4xx on any value not in these lists, so this is the contract.

export const SENIORITY_ENUM = [
	"senior",
	"entry",
	"manager",
	"mid-level",
	"director",
	"c_suite",
	"owner",
	"intern",
	"founder",
	"head",
	"vp",
	"partner",
] as const;

export const FUNCTION_ENUM = [
	"operations",
	"support",
	"engineering",
	"sales",
	"education",
	"information_technology",
	"finance",
	"entrepreneurship",
	"administrative",
	"consulting",
	"marketing",
	"arts_and_design",
	"product_management",
	"human_resources",
	"legal",
	"business_development",
	"media_and_communication",
	"data_science",
	"accounting",
] as const;

export const INDUSTRY_ENUM = [
	"it services and it consulting",
	"software development",
	"hospitals and health care",
	"financial services",
	"higher education",
	"retail",
	"government administration",
	"banking",
	"construction",
	"business consulting and services",
	"real estate",
	"motor vehicle manufacturing",
	"insurance",
	"truck transportation",
	"advertising services",
	"telecommunications",
	"education administration programs",
	"non-profit organizations",
	"oil and gas",
	"pharmaceutical manufacturing",
	"manufacturing",
	"hospitality",
	"food and beverage services",
	"law practice",
	"industrial machinery manufacturing",
	"utilities",
	"appliances, electrical, and electronics manufacturing",
	"food and beverage manufacturing",
	"wellness and fitness services",
	"research services",
	"primary and secondary education",
	"chemical manufacturing",
	"machinery manufacturing",
	"staffing and recruiting",
	"medical equipment manufacturing",
	"airlines and aviation",
	"defense and space manufacturing",
	"mining",
	"biotechnology research",
	"restaurants",
	"environmental services",
	"accounting",
	"retail apparel and fashion",
	"entertainment providers",
	"civil engineering",
	"wholesale building materials",
	"wholesale",
	"aviation and aerospace component manufacturing",
	"travel arrangements",
	"automation machinery manufacturing",
	"human resources services",
	"renewable energy semiconductor manufacturing",
	"architecture and planning",
	"outsourcing and offshoring consulting",
	"facilities services",
	"semiconductor manufacturing",
	"civic and social organizations",
	"spectator sports",
	"armed forces",
	"design services",
	"consumer services",
	"professional training and coaching",
	"individual and family services",
	"broadcast media production and distribution",
	"mental health care",
	"personal care product manufacturing",
	"farming",
	"technology, information and internet",
	"computers and electronics manufacturing",
	"security and investigations",
	"international trade and development",
	"transportation, logistics, supply chain and storage",
	"media production",
	"events services",
	"medical practices",
	"information services",
	"e-learning providers",
	"computer and network security",
	"packaging and containers manufacturing",
	"textile manufacturing",
	"retail luxury goods and jewelry",
	"furniture and home furnishings manufacturing",
	"book and periodical publishing",
	"law enforcement",
	"computer games",
	"plastics manufacturing",
	"computer hardware manufacturing",
	"public safety",
	"musicians",
	"beverage manufacturing",
	"printing services",
	"public relations and communications services",
	"paper and forest product manufacturing",
	"retail office equipment",
	"venture capital and private equity principals",
	"religious institutions",
	"international affairs",
	"government relations services",
	"freight and package transportation",
	"museums, historical sites, and zoos",
	"market research",
	"newspaper publishing",
	"gambling facilities and casinos",
	"online audio and video media",
	"executive offices",
	"administration of justice",
	"investment banking",
	"legal services",
	"performing arts",
	"glass, ceramics and concrete manufacturing",
	"photography",
	"recreational facilities",
	"graphic design",
	"translation and localization",
	"shipbuilding",
	"maritime transportation",
	"political organizations",
	"artists and writers",
	"animation and post-production",
	"investment management",
	"wholesale import and export",
	"libraries",
	"sporting goods manufacturing",
	"think tanks",
	"railroad equipment manufacturing",
	"writing and editing",
	"veterinary services",
	"retail groceries",
	"fundraising",
	"alternative medicine",
	"leasing non-residential real estate",
	"tobacco manufacturing",
	"movies, videos, and sound",
	"legislative offices",
	"retail art supplies",
	"public policy offices",
	"computer networking products",
	"warehousing and storage",
	"fisheries",
	"philanthropic fundraising services",
	"nanotechnology research",
	"strategic management services",
	"capital markets",
	"dairy product manufacturing",
	"ranching",
	"wireless services",
	"alternative dispute resolution",
	"mobile gaming apps",
] as const;

export const DEPARTMENT_ENUM = [
	"operations",
	"executive",
	"sales",
	"engineering_technical",
	"founder",
	"teacher",
	"office_operations",
	"technician",
	"customer_service_support",
	"project_management",
	"finance",
	"information_technology",
	"operations_executive",
	"consultant",
	"store_operations",
	"all_design",
	"software_development",
	"professor",
	"medicine",
	"support_technical_services",
	"marketing",
	"construction",
	"logistics",
	"business_development",
	"accounting",
	"legal",
	"human_resources",
	"finance_executive",
	"account_management",
	"principal",
	"research_development",
	"financial_planning_analysis",
	"nursing",
	"graphic_design",
	"quality_assurance",
	"sales_operations",
	"data_science",
	"facilities_management",
	"medical_administration",
	"compliance",
	"sales_executive",
	"legal_operations",
	"industrial_engineering",
	"governmental_affairs_regulatory_law",
	"it_operations",
	"doctors_physicians",
	"real_estate",
	"social_work",
	"information_security",
	"application_development",
	"digital_marketing",
	"sourcing_procurement",
	"marketing_communications",
	"medical_education_training",
	"health_safety",
	"psychology",
	"recruiting_talent_acquisition",
	"learning_development",
	"infrastructure",
	"corporate_strategy",
	"test_quality_assurance",
	"help_desk_desktop_services",
	"information_technology_executive",
	"customer_success",
	"internal_audit_control",
	"supply_chain",
	"web_development",
	"marketing_operations",
	"product_mangement",
	"product_development",
	"it_strategy",
	"safety",
	"business_intelligence",
	"content_marketing",
	"legal_executive",
	"public_relations",
	"enterprise_architecture",
	"enterprise_resource_planning",
	"social_media_marketing",
	"field_outside_sales",
	"project_program_management",
	"artificial_intelligence_machine_learning",
	"networking",
	"quality_management",
	"chemical_engineering",
	"sales_engineering",
	"physical_security",
	"talent_management",
	"physical_therapy",
	"technology_operations",
	"product_ui_ux_design",
	"medical_health_executive",
	"emerging_technology_innovation",
	"ui_ux",
	"marketing_executive",
	"brand_management",
	"pharmacy",
	"digital_transformation",
	"call_center",
	"medical_research",
	"project_development",
	"public_health",
	"search_engine_optimization_pay_per_click",
	"governance",
	"first_responder",
	"event_marketing",
	"strategic_communications",
	"mechanic",
	"compensation_benefits",
	"customer_experience",
	"mergers_acquisitions",
	"tax",
	"cloud_mobility",
	"database_administration",
	"dentistry",
	"hr_business_partner",
	"shared_services",
	"advertising",
	"partnerships",
	"telecommunications",
	"devops",
	"pathology",
	"financial_risk",
	"legal_counsel",
	"marketing_analytics_insights",
	"lawyer_attorney",
	"nutrition_dietetics",
	"inside_sales",
	"investor_relations",
	"superintendent",
	"servers",
	"mobile_development",
	"ecommerce_development",
	"sales_training",
	"organizational_development",
	"product_marketing",
	"contracts",
	"employee_labor_relations",
	"business_service_management_itsm",
	"radiology",
	"real_estate_finance",
	"human_resource_information_system",
	"human_resources_executive",
	"corporate_secretary",
	"field_marketing",
	"ecommerce_marketing",
	"scrum_master_agile_coach",
	"pediatrics",
	"it_audit_it_compliance",
	"treasury",
	"litigation",
	"data_center",
	"people_operations",
	"clinical_systems",
	"culture_diversity_inclusion",
	"financial_reporting",
	"leasing",
	"it_training",
	"lead_generation",
	"demand_generation",
	"revenue_operations",
	"customer_retention_development",
	"it_asset_management",
	"it_procurement",
	"channel_sales",
	"data_warehouse",
	"oncology",
	"hr_financial_erp_systems",
	"financial_strategy",
	"financial_systems",
	"opthalmology",
	"anesthesiology",
	"psychiatry",
	"orthopedics",
	"bioengineering",
	"obstetrics_gynecology",
	"optometry",
	"intellectual_property_patent",
	"neurology",
	"labor_employment",
	"acquisitions",
	"sales_enablement",
	"dermatology",
	"workforce_mangement",
	"chiropractics",
	"retail_store_systems",
	"customer_marketing",
	"storage_disaster_recovery",
	"technical_marketing",
	"privacy",
	"ediscovery",
	"virtualization",
	"epidemiology",
	"infectious_disease",
	"ethics",
	"biometrics",
	"collaboration_web_app",
] as const;

export const APOLLO_SENIORITY_ENUM = [
	"owner",
	"founder",
	"c_suite",
	"partner",
	"vp",
	"head",
	"director",
	"manager",
	"senior",
	"entry",
	"intern",
] as const;

export type Seniority = (typeof SENIORITY_ENUM)[number];
export type Func = (typeof FUNCTION_ENUM)[number];
export type Industry = (typeof INDUSTRY_ENUM)[number];
export type Department = (typeof DEPARTMENT_ENUM)[number];
