/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewIndexRouteImport } from './routes/new.index'
import { Route as NewThinkingRouteImport } from './routes/new.thinking'
import { Route as NewPasteRouteImport } from './routes/new.paste'
import { Route as NewFormRouteImport } from './routes/new.form'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewThinkingRoute = NewThinkingRouteImport.update({
  id: '/new/thinking',
  path: '/new/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPasteRoute = NewPasteRouteImport.update({
  id: '/new/paste',
  path: '/new/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const NewFormRoute = NewFormRouteImport.update({
  id: '/new/form',
  path: '/new/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/new/form': typeof NewFormRoute
  '/new/paste': typeof NewPasteRoute
  '/new/thinking': typeof NewThinkingRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/new/form': typeof NewFormRoute
  '/new/paste': typeof NewPasteRoute
  '/new/thinking': typeof NewThinkingRoute
  '/new': typeof NewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/new/form': typeof NewFormRoute
  '/new/paste': typeof NewPasteRoute
  '/new/thinking': typeof NewThinkingRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/authenticated'
    | '/new/form'
    | '/new/paste'
    | '/new/thinking'
    | '/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/authenticated'
    | '/new/form'
    | '/new/paste'
    | '/new/thinking'
    | '/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/_authenticated/authenticated'
    | '/new/form'
    | '/new/paste'
    | '/new/thinking'
    | '/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRoute
  NewFormRoute: typeof NewFormRoute
  NewPasteRoute: typeof NewPasteRoute
  NewThinkingRoute: typeof NewThinkingRoute
  NewIndexRoute: typeof NewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/thinking': {
      id: '/new/thinking'
      path: '/new/thinking'
      fullPath: '/new/thinking'
      preLoaderRoute: typeof NewThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/paste': {
      id: '/new/paste'
      path: '/new/paste'
      fullPath: '/new/paste'
      preLoaderRoute: typeof NewPasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/form': {
      id: '/new/form'
      path: '/new/form'
      fullPath: '/new/form'
      preLoaderRoute: typeof NewFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRoute,
  NewFormRoute: NewFormRoute,
  NewPasteRoute: NewPasteRoute,
  NewThinkingRoute: NewThinkingRoute,
  NewIndexRoute: NewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
